# Generated by Django 2.1 on 2017-12-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_text',
        ),
    ]
