# Generated by Django 2.1 on 2017-12-28 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugcontext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(max_length=100)),
                ('bug_body', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('excerpt', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bugid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Buglevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='bugcontext',
            name='bug_levels',
            field=models.ManyToManyField(blank=True, to='jira.Buglevel'),
        ),
        migrations.AddField(
            model_name='bugcontext',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.Category'),
        ),
    ]
