# Generated by Django 2.1 on 2017-12-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_auto_20171229_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugid',
            old_name='name',
            new_name='bugid_id',
        ),
        migrations.RenameField(
            model_name='buglevel',
            old_name='name',
            new_name='buglevel_text',
        ),
    ]
